version: '3.7'
services:
  db1:
    image: postgres:latest
    volumes:
      - ./.docker/db1/postgres/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: sandbox
    ports:
      - '5433:5432' # 5433 port
  db2:
    image: postgres:latest
    volumes:
      - ./.docker/db2/postgres/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: sandbox
    ports:
      - '5434:5432' # 5434 port
