// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Posts    string
	Roles    string
	Sessions string
	UserRole string
	Users    string
}{
	Posts:    "posts",
	Roles:    "roles",
	Sessions: "sessions",
	UserRole: "user_role",
	Users:    "users",
}
