// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Posts", testPostsUpsert)

	t.Run("Roles", testRolesUpsert)

	t.Run("Sessions", testSessionsUpsert)

	t.Run("UserRoles", testUserRolesUpsert)

	t.Run("Users", testUsersUpsert)
}
